apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: aws-cli-openshift
spec:
  schedule: "*/10 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:             
    spec:     
      template:         
        metadata:
          name: aws-cli-openshift
        spec:
          containers:
          - name: aws-cli-openshift
            image: docker-registry.default.svc:5000/<your-project-name>/aws-cli
            volumeMounts:
            - mountPath: /data
              name: storagedata
          volumes:
          - name: storagedata
            persistentVolumeClaim:
              claimName: <your-PVC-name>
          restartPolicy: Never
              
